spring:
  application:
    name: narspi-gtw-ja

  rabbitmq:
    host:
    port:
    username:
    password:

    publisher-confirm-type: correlated

    publisher-returns: true

    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        concurrency: 1
        max-concurrency: 5


server:
  port: 8080

  servlet:
    context-path: /api